	
	
var aiIdeas = ["learn an instrument",
"play an instrument",
"learn a language",
"learn morse code",
"catch up with a show",
"finish the show you never did",
"bake a cake",
"spa day",
"re-organise your closet",
"clean your desk",
"read a book",
"blast your favourite song on full volume",
"sing to yourself",
"oil painting",
"acrylic painting",
"look at old pictures",
"sort out your phone photo album",
"write a letter to your future self",
"doodling",
"plan a trip",
"buy plants",
"meditation",
"play solitaire",
"take a long bath",
"light up some candles",
"marie kondo your room/home",
"online shopping",
"print your favourite photos",
"build a fort",
"dance",
"knitting",
"crochet",
"work on a puzzle",
"sleep.",
"make yourself a cup of tea",
"listen to a podcast",
"read a blog",
"make a mood board",
"make a vision board",
"redecorate your room",
"create a photo collage",
"adult colouring book",
"catchup with an old friend",
"learn a new skill",
"play online trivia",
"watch youtube videos"];
function showDivAI(){	
	var aiIdea = aiIdeas[Math.floor(Math.random() * aiIdeas.length)];
	console.log(aiIdea);
	document.getElementById('ai').textContent = aiIdea;
	document.getElementById('ai').style.display = "block";
}


var aoIdeas = ["running",
"jogging",
"journalling",
"make a nice lunch/dinner",
"learn to cook a fancy meal",
"go to a bookstore",
"take a hike",
"a long drive",
"solo day trip",
"volunteer",
"go for a long walk",
"solo picnic",
"visit your favourite coffee shop",
"go shopping",
"go to the local park",
"eat at your favourite restaurant",
"go thrifting",
"visit a garden",
"go to a cat cafe",
"take photographs",
"go to the bar",
"go window shopping"];
function showDivAO(){	
	var aoIdea = aoIdeas[Math.floor(Math.random() * aoIdeas.length)];
	console.log(aoIdea);
	document.getElementById('ao').textContent = aoIdea;
	document.getElementById('ao').style.display = "block";
}

var wfiIdeas = ["karaoke",
"watch horror movies",
"bake a cake",
"facemask",
"play monopoly",
"movie marathon",
"movie themed party",
"decade themed party",
"play scrabbles",
"play clue",
"play charades",
"play snakes and ladder",
"create a custom charades",
"make cookies",
"cooking competition",
"play video games",
"go to the grocery store",
"try a new drink or snack",
"photoshoot",
"eat ice cream",
"indoor photoshoot",
"play chess",
"try out a craft",
"fix yourselves a drink",
"dance",
"play darts",
"play poker",
"make music",
"pillow fight",
"try a new recipe",
"make pizza",
"decorate cookies",
"make a dessert",
"make a smoothie",
"play truth or dare",
"play would you rather",
"camp in the yard",
"make cheese fondue",
"make chocolate fondue",
"cook a dish from another country",
"movie night with snacks",
"afternoon tea",
"make a cocktail/mocktail",
"prank calls",
"disney movies marathon",
"binge a tv show",
"have a cook-off",
"have a bake-off",
"2016 youtube challenges",
"gossip ;)",
"listen to christmas music",
"sing-off",
"friendship bracelet",
"just dance",
"fashion show",
"make popsicles",
"prank call fast food chains",
"do manicures",
"do pedicure"];
function showDivWFI(){	
	var wfiIdea = wfiIdeas[Math.floor(Math.random() * wfiIdeas.length)];
	console.log(wfiIdea);
	document.getElementById('wfi').textContent = wfiIdea;
	document.getElementById('wfi').style.display = "block";
}


var wfoIdeas = ["stargazing",
"watch the sunset",
"laser tag",
"swimming",
"waterpark",
"paintballing",
"picnic",
"watch the sunrise",
"lay on the beach",
"cycling",
"go to the theatre",
"take a hike",
"a long drive",
"go to the amusement park",
"trampoline park",
"head to the closet campsite",
"go shopping",
"go to the local park",
"go thrifting",
"play basketball",
"play mini golf",
"play badminton",
"play tennis",
"visit an arcade",
"see a play or musical",
"take photographs",
"visit an escape room",
"go to an arcade",
"get ice cream",
"go rollerskating",
"visit a garden",
"visit a jazz cafe",
"tie-dye clothing",
"go on a one day road trip",
"film a vlog",
"go fishing",
"host a barbecue",
"visit tourist destinations in your town",
"indoor skydiving",
"go to the bar",
"indoor rock climbing",
"visit an aquarium",
"photoshoot at unpopular locations",
"play dodgeball",
"go window shopping",
"go fruit picking",
"ride scooters",
"go on a boat ride",
"feed local ducks",
"go to a cat cafe",
"dine at a concept restaurant",
"go paddle boarding",
"make ice cream sundays",
"go to a drive through coffee shop",
"go to a drive through fast food chain",
"dine at a new restaurant",
"check out a view point",
"play with a frisbee",
"play pool",
"create a time capsule",
"visit a petting zoo",
"try food from another country",
"drive go-carts",
"drive-in movie",
"go somewhere you’ve never been",
"try an extreme sport",
"play on a kids playground",
"geocache",
"ding dong ditch",
"water balloon fight",
"order a food not on the menu at a restaurant, like diet water",
"play a prank in public"];
function showDivWFO(){	
	var wfoIdea = wfoIdeas[Math.floor(Math.random() * wfoIdeas.length)];
	console.log(wfoIdea);
	document.getElementById('wfo').textContent = wfoIdea;
	document.getElementById('wfo').style.display = "block";
}
